# Model arguments
model_name_or_path: Qwen/Qwen2.5-1.5B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: open-r1/OpenR1-Math-220k # gsm8k
dataset_configs:
- default
# Num processes is less by 1 as vLLM is using 1 GPU
num_processes: 1

# GRPO trainer config
bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.9
do_eval: false
eval_strategy: steps
eval_steps: 100
save_steps: 250
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 512
max_completion_length: 1024
max_steps: -1
num_generations: 8
num_train_epochs: 1
output_dir: /usr/project/xtmp/rx55/projects/long_cot/results/open-r1/models/Qwen2.5-1.5B-Open-R1-GRPO-gsm8k-8gen-t
hub_model_id: Qwen2.5-1.5B-Open-R1-GRPO-gsm8k-8gen-t
run_name: Qwen2.5-1.5B-Open-R1-GRPO-gsm8k-8gen-t
overwrite_output_dir: true
per_device_eval_batch_size: 16
per_device_train_batch_size: 8
push_to_hub: true
report_to:
- wandb
save_strategy: "no"
seed: 42
warmup_ratio: 0.1
